# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Severin Jr Ndema-Moussa #Alpha
email: severin.jr.n.m@gmail.com #youremailaddress@gmail.com
description: CREAM #The Jekyll version of the Alpha theme by HTML5 UP.
baseurl: /cream #"/alpha-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://jpamphile.github.io" #"https://andrewbanchich.gitlab.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: #andrewbanchich
twitter_username: #andrewbanchich
facebook_URL: www.facebook.com/cesarrimyemery?fref=mentions&_tn_=K-R
instagram_username:

# Build settings
markdown: kramdown
